import { Match } from "./match.model";

export const ALL_MATCHES: Match[] =
    [
        { "id": 1, "date": "June/11   21:00", "home": "Turkey", "away": "Italy" },
        { "id": 2, "date": "June/12   15:00", "home": "Wales", "away": "Switzerland" },
        { "id": 13, "date": "June/16   18:00", "home": "Turkey", "away": "Wales" },
        { "id": 14, "date": "June/16   21:00", "home": "Italy", "away": "Switzerland" },
        { "id": 25, "date": "June/20   18:00", "home": "Switzerland", "away": "Turkey" },
        { "id": 26, "date": "June/20   18:00", "home": "Italy", "away": "Wales" },
        { "id": 3, "date": "June/12  18:00", "home": "Denmark", "away": "Finland" },
        { "id": 4, "date": "June/12  21:00", "home": "Belgium", "away": "Russia" },
        { "id": 15, "date": "June/16  15:00", "home": "Finland", "away": "Russia" },
        { "id": 16, "date": "June/17  18:00", "home": "Denmark", "away": "Belgium" },
        { "id": 27, "date": "June/21  21:00", "home": "Russia", "away": "Denmark" },
        { "id": 28, "date": "June/21  21:00", "home": "Finland", "away": "Belgium" },
        { "id": 6, "date": "June/13  18:00", "home": "Austria", "away": "North Macedonia" },
        { "id": 5, "date": "June/13  21:00", "home": "Netherlands", "away": "Ukraine" },
        { "id": 18, "date": "June/17  15:00", "home": "Ukraine", "away": "North Macedonia" },
        { "id": 17, "date": "June/17  21:00", "home": "Netherlands", "away": "Austria" },
        { "id": 29, "date": "June/21  18:00", "home": "North Macedonia", "away": "Netherlands" },
        { "id": 30, "date": "June/21  18:00", "home": "Ukraine", "away": "Austria" },
        { "id": 7, "date": "June/13  15:00", "home": "England", "away": "Croatia" },
        { "id": 8, "date": "June/14  15:00", "home": "Scotland", "away": "Czech Republic" },
        { "id": 19, "date": "June/18  18:00", "home": "Croatia", "away": "Czech Republic" },
        { "id": 20, "date": "June/18  21:00", "home": "England", "away": "Scotland" },
        { "id": 31, "date": "June/22  21:00", "home": "Croatia", "away": "Scotland" },
        { "id": 32, "date": "June/22  21:00", "home": "Czech Republic", "away": "England" },
        { "id": 10, "date": "June/14  18:00", "home": "Poland", "away": "Slovakia" },
        { "id": 9, "date": "June/14  21:00", "home": "Spain", "away": "Sweden" },
        { "id": 21, "date": "June/18  15:00", "home": "Sweden", "away": "Slovakia" },
        { "id": 22, "date": "June/19  21:00", "home": "Spain", "away": "Poland" },
        { "id": 33, "date": "June/23  18:00", "home": "Slovakia", "away": "Spain" },
        { "id": 34, "date": "June/23  18:00", "home": "Sweden", "away": "Poland" },
        { "id": 11, "date": "June/15  18:00", "home": "Hungary", "away": "Portugal" },
        { "id": 12, "date": "June/15  21:00", "home": "France", "away": "Germany" },
        { "id": 23, "date": "June/19  15:00", "home": "Hungary", "away": "France" },
        { "id": 24, "date": "June/19  18:00", "home": "Portugal", "away": "Germany" },
        { "id": 35, "date": "June/23  21:00", "home": "Portugal", "away": "France" },
        { "id": 36, "date": "June/23  21:00", "home": "Germany", "away": "Hungary" }
    ]